// <auto-generated />
using System;
using ASPE.DQM.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASPE.DQM.Migrations.Model
{
    [DbContext(typeof(ModelDataContext))]
    [Migration("20190325155836_InitalModelSchema")]
    partial class InitalModelSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASPE.DQM.Model.Visualization", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppID");

                    b.Property<string>("Description");

                    b.Property<bool>("Published");

                    b.Property<bool>("RequiresAuth");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Visualizations");
                });
#pragma warning restore 612, 618
        }
    }
}
